permalink: /:categories/:title.html
# url: "https://jackysuper.github.io/"
full_name: "Best Apps"
first_name: "Best"
last_name: "App"
blog_title: "Best App"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "Best App"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Find Best App"
twitter: ""
github: ""
facebook: ""
linkined_url: ""
